# Use existing conda environments (must be the same names) or create new ones just for this pipeline?
conda_envs:
  use_existing_envs: true
  envs_path: '~/work/miniforge3/envs/' # path to conda envs if use_existing_envs is true

# Use Ensembl IDs instead of gene names in the analysis?
# Most tools, pipelines and tutorials, such as in the Seurat and the ScanPy framework, seem to use gene names by default, either by summing up cell counts with different Ensembl IDs per gene name, which is very debatable, or by adding suffices to the gene names to make them unique. The latter case is not a problem, but the form
use_ensembl_ids: true

data:
  samples_in_directory: false # boolean, are samples or their symlinks in resource/data?
  # if previous is false, give path to sample sheet
  sample_sheet_path: 'resources/sample_sheet.tsv' # tab-separated columns: sample_name|path

# Count matrix/layer to use for analysis downstream of normalization
count_layer: ['soupX_counts', 'counts'] # usually 'soupX_counts' or 'counts'
# count_layer: ['counts'] # usually 'soupX_counts' or 'counts'

# quality control method to use
# 'theislab_tutorial', 'theislab_tutorial_then_scAutoQC' or 'scAutoQC' (which failed miserably in my case)
# only choose one of the methods including scAutoQC
qc_method: ['theislab_tutorial', 'scAutoQC']

subset:
  use: False # perform analysis after merging of samples on subset (true) or full (false) dataset?
  fraction: 0.2 # fraction of cells to use for subset analysis

# different methods for dimensionality reduction of the merged data
dim_reduc:
  normalization: 'log1p_norm'
  scale_data_before_pca: [True, False] # scale data before PCA?
  genes_for_pca: ['all', 'globally_highly_variable', 'highly_variable_per_sample'] # which genes to use for PCA
  cc_method: ['None', 'regress_out', 'cc_genes_out', 'cc_difference_regressed_out', 'cPCA'] # method to remove cell cycle effect
  pca_n_components: 50 # number of components to use for PCA
  umap_n_neighbors: 30 # number of neighbors to use for UMAP

chosen_parameters:
  count_layer: 'counts' # count layer to use for analysis
  qc_method: 'scAutoQC' # quality control method to use
  normalization: 'log1p_norm' # normalization method to use
  scale_data_before_pca: False # scale data before PCA?
  genes_for_pca: 'highly_variable_per_sample' # genes to use for PCA
  cc_method: 'cc_genes_out' # potential cell cycle removal method
  pca_n_components: 50 # number of PCA components to use
  umap_n_neighbors: 30 # number of neighbors to use for UMAP

# chosen_branch: 'results/merged/dim_reduc_potential_cc_removal/count_layer__counts/normalization__log1p_norm/scale_data_before_pca__False/genes_for_pca__highly_variable_per_sample/cc_method__cc_genes_out/pca_n_components__50/umap_n_neighbors__30/qc_method__scAutoQC'

chosen_clustering: 'results/merged/chosen_branch/RNA_snn_wo_1_5_6_res.0.3.csv'

use_metacells: False # use metacells for analysis?
# used for metacell computation
# chosen_parameters:
  # count_layer: 'counts'
  # qc_method: 'theislab_tutorial'

set-resources:
  CellUntangler:
    slurm_extra: "'--gres=gpu:tesla:2'"